export const Strings ={
    starterText: ' Find your Comfort\nFood here',
    starterDescription: 'Here you can order food and read \n about its ingredients. Enjoy!',
    buttonText: 'Next',
    comfortFood: 'Food Ninja is Where Your\nComfort Food Lives',
    fastAndSmoothDelivery: 'Enjoy a fast and smooth food delivery at\nyour doorstep',
    loginToYourAcc:'Login To Your Account',
    orContinueWith: 'Or Continue With',
    Facebook: 'Facebook',
    Google: 'Google',
    Gmail: 'Gmail',
    forgotPassword: 'Forgot Your Password?',
    findYourFvrtFood: 'Find Your\nFavorite Food',
    noAddonsAvailable: 'No add-ons available',
    availableAddOn:'Available Add-ons',
    confirmationMsg: 'Are you sure you want to remove this item?',
    addOn:'Add-On: ',
    cartEmptyMsg:'Cart is empty.',
    myCart:'My Cart',
    subTotal:'Sub Total:',
    deliveryCharges:'Delivery Charges:',
    discount:'Discount',
    total:'Total',
    alreadyHaveAnAccount: 'Already have an account?',
    keepMeSignedIn:'Keep me signed in',
    emailMeAboutSpecialPricing:'Email me about special pricing',
    dontHaveAnAccount:'Sign up',
    
}

export const ScreenNames={
    Login: 'Login',
    Tutorial: 'TutorialScreen',
    Start:'StartScreen',
    Registeration: 'Register',
    Confirmation: 'Confirmation',
    Tabs:'tabs',
    Dashboard:'Dashboard',
    Vegan:'Vegan', 
    Fastfood:'Fastfood',
    Drink:'Drink',
    Sides:'Sides',
    AuthStack:'AuthStack',
    BottomStack:'BottomStack',
    Home:'Home',
    Profile:'Profile',
    Cart:'Cart',
    Chat:'Chat',



}